# Basic Information
title: Dong-Dong Wu
# chinese_name: 吴东冬
position: Ph.D. Student
affiliation: The University of Tokyo
# email: 

# Search Engine Optimization (SEO)
keywords: Dongdong Wu, machine learning, weakly supervised learning, partial label learning, diffusion model
description: Dongdong Wu is a PhD student at The University of Tokyo. His research interests include Weakly Supervised Learning, Data-efficient Learning, AI Safety and Uncertainty in Large Model.
canonical: https://wu-dd.github.io/

# Links
google_scholar: https://scholar.google.com/citations?hl=zh-CN&user=_Vx3dZgAAAAJ
# cv_link: assets/files/curriculum_vitae.pdf
github_link: https://github.com/wu-dd
linkedin: https://www.linkedin.com/in/dongdong-wu-5a332b27a/
# twitter:
# bilibili: https://space.bilibili.com/3546681717033402

# Images (e.g., your profile picture and your website's favicon)
avatar: /assets/img/profile1.jpg
favicon: /assets/img/favicon.png
favicon_dark: /assets/img/favicon-dark.png

# Footnote
enable_footnote: true

# Auto Dark Mode
auto_dark_mode: false

# Font
font: "Serif" # or "Sans Serif"

# Google Analytics ID
google_analytics: _Vx3dZgAAAAJ

# Use this project as a remote theme for GitHub Pages
remote_theme: yaoyao-liu/minimal-light

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
  - temp/
